export const PAYMENT_BANKS = [
  { id: "VCB", bin: "970436", label: "Vietcombank", shortName: "Vietcombank" },
  { id: "AGR", bin: "970405", label: "Agribank", shortName: "Agribank" },
  { id: "ICB", bin: "970415", label: "VietinBank", shortName: "VietinBank" },
  { id: "BIDV", bin: "970418", label: "BIDV", shortName: "BIDV" },
  { id: "MB", bin: "970422", label: "MB Bank", shortName: "MBBank" },
  { id: "TCB", bin: "970407", label: "Techcombank", shortName: "Techcombank" },
  { id: "ACB", bin: "970416", label: "ACB", shortName: "ACB" },
  { id: "VPB", bin: "970432", label: "VPBank", shortName: "VPBank" },
  { id: "TPB", bin: "970423", label: "TPBank", shortName: "TPBank" },
  { id: "STB", bin: "970403", label: "Sacombank", shortName: "Sacombank" },
  { id: "HDB", bin: "970437", label: "HDBank", shortName: "HDBank" },
  { id: "VIB", bin: "970441", label: "VIB", shortName: "VIB" },
  { id: "SHB", bin: "970443", label: "SHB", shortName: "SHB" },
  { id: "EIB", bin: "970431", label: "Eximbank", shortName: "Eximbank" },
  { id: "MSB", bin: "970426", label: "MSB", shortName: "MSB" },
  { id: "OCB", bin: "970448", label: "OCB", shortName: "OCB" },
  { id: "LPB", bin: "970449", label: "LienVietPostBank", shortName: "LienVietPostBank" },
  { id: "NAB", bin: "970428", label: "Nam A Bank", shortName: "NamABank" },
  { id: "PGB", bin: "970430", label: "PGBank", shortName: "PGBank" },
  { id: "VCCB", bin: "970454", label: "Bản Việt Bank", shortName: "VietCapitalBank" },
  { id: "BAB", bin: "970409", label: "Bắc Á Bank", shortName: "BacABank" },
  { id: "SEAB", bin: "970440", label: "SeABank", shortName: "SeABank" },
  { id: "CAKE", bin: "546034", label: "cake by VPBank", shortName: "cake" },
  { id: "IVB", bin: "970434", label: "Indovina Bank", shortName: "IndovinaBank" },
  { id: "VAB", bin: "970427", label: "Việt Á Bank", shortName: "VietABank" },
  { id: "KLB", bin: "970452", label: "KiênLong Bank", shortName: "KienLongBank" },
  { id: "ABB", bin: "970425", label: "AnBình Bank", shortName: "ABBank" },
  { id: "VBB", bin: "970433", label: "Việt Bank", shortName: "VietBank" },
  { id: "BVB", bin: "970438", label: "BaoViet Bank", shortName: "BaoVietBank" },
  { id: "SGCB", bin: "970400", label: "Saigonbank", shortName: "Saigonbank" },
  { id: "NCB", bin: "970419", label: "NCB", shortName: "NCB" },
  { id: "SGB", bin: "970400", label: "Saigon Bank", shortName: "SGB" },
  { id: "OJB", bin: "970414", label: "OceanBank", shortName: "Oceanbank" },
  { id: "PBVN", bin: "970412", label: "PVcomBank", shortName: "PVcomBank" },
  { id: "VDB", bin: "007", label: "VDB", shortName: "VDB" },
  { id: "COOPBANK", bin: "970446", label: "COOPBANK", shortName: "COOPBANK" },
];

export const PAYMENT_BANK_INFO = {
  accountNumber: "0328959755",
  accountName: "CÔNG TY SWEETSTAR",
  prefix: "SWEETSTAR",
};

export const getPaymentBankLogo = (code) => `https://cdn.vietqr.io/img/${code}.png`;
